config/routes.rb
Blog::Application.routes.draw do
  # get "/kiwis", to: "kiwis#index"
  # get "/kiwis/new", to: "kiwis#new"
  # post "/kiwis/post", to: "kiwis#create"
  # get "/kiwis/:id", to: "kiwis#show"
  # # delete "/kiwis/:id", to: "kiwis#delete"
  resources :kiwis
end

app/models/kiwi.rb
class Kiwis < ActiveRecord::Base
end

app/models/post.rb
class Kiwi <AcitveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/kiwi_controller.rb
class KiwisController < ApplicationController

	def index
		@kiwis = Kiwi.all
	end

	def show
		@kiwi = Kiwi.find(params[:id])
	end

	def new
		@kiwi = Kiwi.new
	end

	def create
		@kiwi = Kiwi.find(params[:kiwi])
		if @kiwi.save
			redirect_to @kiwis
		end
			render new
		end
	end

	def destroy
		@kiwi = Kiwi.find(params[:id])
		@kiwi.destroy
	end

end

app/controllers/kiwis_controller.rb
class KiwisController < ApplicationController

	def index
		@kiwis = Kiwi.all
	end

	def show
		@kiwi = Kiwi.find(params[:id])
	end

	def new
		@kiwis = Kiwi.new
	end

	def create
		@kiwi = Kiwi.find(params[:kiwi])
		if @kiwi.save
			redirect_to @kiwi
		else
			render new
		end
	end

	def destroy
		@kiwi = Kiwi.find(params[:id])
		@kiwi.destroy
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kiwis/_form.html.haml
= form_for(@kiwi) do |f|
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions
    = f.submit 'Save'

app/views/kiwis/index.html.haml
%h1 Listing Kiwis

%table
  %tr
    %th Title
    %th Body
    %th
    %th
    %th

  - @kiwis.each do |kiwi|
    %tr
      %td= kiwi.title
      %td= kiwi.body
      %td= link_to 'Show', kiwi, {:class => "kiwi"}
      %td= link_to 'Edit', edit_kiwi_path(kiwi)
      %td= link_to 'Destroy', kiwi, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to('New Post', "/kiwis/new")

app/views/kiwis/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @kiwi.title
%p
  %b Body:
  = @kiwi.body

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %tr
    %th Title
    %th Body
    %th
    %th
    %th

  - @kiwis.each do |kiwi|
    %tr
      %td= kiwi.title
      %td= kiwi.body
      %td= link_to 'Show', kiwi, {:class => "blake"}
      %td= link_to 'Edit', edit_kiwi_path(kiwi)
      %td= link_to 'Destroy', kiwi, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to('New Post', "/kiwis/new")